<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Data;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $filter
     * @return Data[]
     */
    public function getDataByFilter(array $filter) {
        /**
         * @var Data[] $data
         */
        $data = $this->findBy($filter);
        return $data;
    }
}
